version: "3.8"

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./script/seed.psql:/var/script
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/database
      SERVER_PORT: 3002
    ports:
      - "3002:3002"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
